/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as ApiUploadsUploadIdRouteImport } from './routes/api/uploads/$uploadId'
import { Route as ApiUploadsUploadIdPartsPartNumberRouteImport } from './routes/api/uploads/$uploadId/parts/$partNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsUploadIdRoute = ApiUploadsUploadIdRouteImport.update({
  id: '/$uploadId',
  path: '/$uploadId',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiUploadsUploadIdPartsPartNumberRoute =
  ApiUploadsUploadIdPartsPartNumberRouteImport.update({
    id: '/parts/$partNumber',
    path: '/parts/$partNumber',
    getParentRoute: () => ApiUploadsUploadIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/uploads/$uploadId': typeof ApiUploadsUploadIdRouteWithChildren
  '/api/uploads/$uploadId/parts/$partNumber': typeof ApiUploadsUploadIdPartsPartNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/uploads/$uploadId': typeof ApiUploadsUploadIdRouteWithChildren
  '/api/uploads/$uploadId/parts/$partNumber': typeof ApiUploadsUploadIdPartsPartNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/uploads/$uploadId': typeof ApiUploadsUploadIdRouteWithChildren
  '/api/uploads/$uploadId/parts/$partNumber': typeof ApiUploadsUploadIdPartsPartNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploads'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/uploads/$uploadId'
    | '/api/uploads/$uploadId/parts/$partNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploads'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/uploads/$uploadId'
    | '/api/uploads/$uploadId/parts/$partNumber'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/api/uploads'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/uploads/$uploadId'
    | '/api/uploads/$uploadId/parts/$partNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$uploadId': {
      id: '/api/uploads/$uploadId'
      path: '/$uploadId'
      fullPath: '/api/uploads/$uploadId'
      preLoaderRoute: typeof ApiUploadsUploadIdRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/uploads/$uploadId/parts/$partNumber': {
      id: '/api/uploads/$uploadId/parts/$partNumber'
      path: '/parts/$partNumber'
      fullPath: '/api/uploads/$uploadId/parts/$partNumber'
      preLoaderRoute: typeof ApiUploadsUploadIdPartsPartNumberRouteImport
      parentRoute: typeof ApiUploadsUploadIdRoute
    }
  }
}

interface ApiUploadsUploadIdRouteChildren {
  ApiUploadsUploadIdPartsPartNumberRoute: typeof ApiUploadsUploadIdPartsPartNumberRoute
}

const ApiUploadsUploadIdRouteChildren: ApiUploadsUploadIdRouteChildren = {
  ApiUploadsUploadIdPartsPartNumberRoute:
    ApiUploadsUploadIdPartsPartNumberRoute,
}

const ApiUploadsUploadIdRouteWithChildren =
  ApiUploadsUploadIdRoute._addFileChildren(ApiUploadsUploadIdRouteChildren)

interface ApiUploadsRouteChildren {
  ApiUploadsUploadIdRoute: typeof ApiUploadsUploadIdRouteWithChildren
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsUploadIdRoute: ApiUploadsUploadIdRouteWithChildren,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
